"""
Planner Prompt Test Harness

Evaluates the quality of research plans generated by get_enhanced_plan_prompt
across 10 diverse demo queries. Tests constraint compliance, progressive structure,
independence, angle diversity, and domain adaptation.

Modes:
    DRY RUN (default): Prints generated prompts for manual review, no LLM needed
    LIVE: Uses real LLM when dependencies are available

Usage:
    cd /Users/choclate/Desktop/WORT/deep-research-agent
    python tests/test_planner_prompt.py          # Dry run
    python tests/test_planner_prompt.py --live   # Live LLM testing
"""

import sys
import os
import json
import datetime
import argparse

# ─────────────────────────────────────────────────────────────
# DEMO TEST QUERIES — 10 diverse queries across domains & complexity
# ─────────────────────────────────────────────────────────────
DEMO_QUERIES = [
    {
        "id": 1,
        "domain": "Finance / Fact",
        "complexity": "Narrow",
        "expected_range": "1-2",
        "query": "What is the current price of Bitcoin and what factors are driving it?",
    },
    {
        "id": 2,
        "domain": "Coding / Comparison",
        "complexity": "Moderate",
        "expected_range": "2-4",
        "query": "Compare React and Vue for building interactive dashboards",
    },
    {
        "id": 3,
        "domain": "AI / Technical",
        "complexity": "Broad",
        "expected_range": "4-6",
        "query": "How do large language models work and what are their limitations?",
    },
    {
        "id": 4,
        "domain": "History",
        "complexity": "Broad",
        "expected_range": "4-7",
        "query": "Tell me about the rise and fall of the Roman Empire",
    },
    {
        "id": 5,
        "domain": "Finance / Strategy",
        "complexity": "Moderate",
        "expected_range": "3-5",
        "query": "What are the best investment strategies for beginners in 2025?",
    },
    {
        "id": 6,
        "domain": "Biology / Ethics",
        "complexity": "Broad",
        "expected_range": "4-6",
        "query": "Explain how CRISPR gene editing works and its ethical implications",
    },
    {
        "id": 7,
        "domain": "News / Current Events",
        "complexity": "Broad",
        "expected_range": "4-7",
        "query": "What are the major developments in the Ukraine-Russia conflict this year?",
    },
    {
        "id": 8,
        "domain": "Science / Comprehensive",
        "complexity": "Very Broad",
        "expected_range": "7-10",
        "query": "Explain everything about quantum computing — from basics to current state to future applications",
    },
    {
        "id": 9,
        "domain": "General / Business",
        "complexity": "Moderate",
        "expected_range": "3-5",
        "query": "What are the benefits and drawbacks of remote work for employees and companies?",
    },
    {
        "id": 10,
        "domain": "Writing / How-to",
        "complexity": "Moderate-Broad",
        "expected_range": "3-6",
        "query": "How do I write a compelling novel? Cover structure, character development, and publishing",
    },
]

# ─────────────────────────────────────────────────────────────
# ANALYSIS FUNCTIONS
# ─────────────────────────────────────────────────────────────


def count_words(text: str) -> int:
    """Count words in a string."""
    return len(text.strip().split())


def analyze_plan(query_info: dict, plan: list) -> dict:
    """Analyze a generated plan against quality criteria."""
    results = {
        "query_id": query_info["id"],
        "domain": query_info["domain"],
        "complexity": query_info["complexity"],
        "expected_range": query_info["expected_range"],
        "user_query": query_info["query"],
        "num_queries": len(plan),
        "queries": [],
        "violations": [],
        "scores": {},
    }

    # Check count constraint (1-10)
    if len(plan) < 1:
        results["violations"].append("❌ FAIL: Zero queries generated")
    elif len(plan) > 10:
        results["violations"].append(f"❌ FAIL: {len(plan)} queries exceeds MAX of 10")
    else:
        results["violations"].append(f"✅ PASS: {len(plan)} queries (within 1-10)")

    # Check expected range match
    expected = query_info["expected_range"]
    if "-" in expected:
        low, high = map(int, expected.split("-"))
        if low <= len(plan) <= high:
            results["violations"].append(
                f"✅ PASS: Count {len(plan)} matches expected range {expected}"
            )
        else:
            results["violations"].append(
                f"⚠️  WARN: Count {len(plan)} outside expected range {expected}"
            )

    # Analyze each query
    word_counts = []
    for i, q in enumerate(plan):
        wc = count_words(q)
        word_counts.append(wc)
        q_result = {
            "num": i + 1,
            "word_count": wc,
            "text": q,
            "within_limit": 20 <= wc <= 100,
        }
        results["queries"].append(q_result)

        if wc < 20:
            results["violations"].append(
                f"❌ FAIL: Query {i + 1} too short ({wc} words, min 20)"
            )
        elif wc > 100:
            results["violations"].append(
                f"❌ FAIL: Query {i + 1} too long ({wc} words, max 100)"
            )
        else:
            results["violations"].append(
                f"✅ PASS: Query {i + 1} word count = {wc} (within 20-100)"
            )

    # Word count statistics
    if word_counts:
        results["scores"]["avg_word_count"] = round(
            sum(word_counts) / len(word_counts), 1
        )
        results["scores"]["min_word_count"] = min(word_counts)
        results["scores"]["max_word_count"] = max(word_counts)

    # Check for progressive structure (heuristic)
    if len(plan) >= 3:
        first_half_avg = sum(word_counts[: len(word_counts) // 2]) / (
            len(word_counts) // 2
        )
        second_half_avg = sum(word_counts[len(word_counts) // 2 :]) / max(
            1, len(word_counts) - len(word_counts) // 2
        )
        results["scores"]["progressive_structure"] = (
            "Likely progressive"
            if second_half_avg >= first_half_avg * 0.8
            else "May lack progression"
        )

    # Check independence (heuristic: word overlap between queries)
    overlap_count = 0
    for i in range(len(plan)):
        for j in range(i + 1, len(plan)):
            words_i = set(plan[i].lower().split())
            words_j = set(plan[j].lower().split())
            if words_i & words_j:
                overlap = len(words_i & words_j) / min(len(words_i), len(words_j))
                if overlap > 0.5:
                    overlap_count += 1
    results["scores"]["overlap_score"] = (
        f"{overlap_count} potential overlaps detected"
        if overlap_count > 0
        else "No significant overlaps"
    )

    return results


def print_separator(char="=", length=80):
    print(char * length)


def print_results(results: list):
    """Print formatted analysis results."""
    print_separator()
    print("PLANNER PROMPT TEST RESULTS")
    print(f"Timestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print_separator()

    total_pass = 0
    total_fail = 0

    for r in results:
        print_separator("-", 80)
        print(
            f"TEST #{r['query_id']} | Domain: {r['domain']} | Complexity: {r['complexity']}"
        )
        print(f'User Query: "{r["user_query"]}"')
        print(
            f"Queries Generated: {r['num_queries']} | Expected: {r['expected_range']}"
        )
        print_separator("-", 80)

        for i, q in enumerate(r["queries"]):
            status = "✅" if q["within_limit"] else "❌"
            print(f"\n  Query {q['num']} [{status}] ({q['word_count']} words):")
            print(f"    {q['text'][:150]}{'...' if len(q['text']) > 150 else ''}")

        print(f"\n  --- Scores ---")
        for key, val in r["scores"].items():
            print(f"    {key}: {val}")

        print(f"\n  --- Constraint Checks ---")
        for v in r["violations"]:
            print(f"    {v}")
            if "FAIL" in v:
                total_fail += 1
            elif "PASS" in v:
                total_pass += 1

        print()

    # Summary
    print_separator("=", 80)
    print("SUMMARY")
    print_separator("=", 80)
    print(f"Total Checks: {total_pass + total_fail}")
    print(f"Passed: {total_pass} ✅")
    print(f"Failed: {total_fail} ❌")
    if total_pass + total_fail > 0:
        pass_rate = (total_pass / (total_pass + total_fail)) * 100
        print(f"Pass Rate: {pass_rate:.1f}%")
    print_separator("=", 80)


# ─────────────────────────────────────────────────────────────
# DRY RUN MODE — Prints prompts for manual review
# ─────────────────────────────────────────────────────────────


def run_dry_run(get_enhanced_plan_prompt):
    """Run tests in dry-run mode — prints generated prompts for manual review."""
    print("\n🔍 DRY RUN MODE — Printing generated prompts for manual review\n")

    for i, demo in enumerate(DEMO_QUERIES):
        print_separator("=", 80)
        print(
            f"TEST #{demo['id']}/10 | Domain: {demo['domain']} | Complexity: {demo['complexity']}"
        )
        print(f'User Query: "{demo["query"]}"')
        print_separator("=", 80)

        try:
            prompt = get_enhanced_plan_prompt(
                query=demo["query"],
                skill_instructions="",
                clarification_context=[],
            )

            print("\n📝 GENERATED PROMPT (first 500 chars):")
            print(prompt[:500])
            print("...")
            print(f"\n📏 Total prompt length: {len(prompt)} characters")

            # Check for key elements in prompt
            checks = [
                ("Hard constraints section", "HARD CONSTRAINTS" in prompt),
                ("Query count framework", "DECIDE HOW MANY" in prompt),
                ("Domain adaptation", "ADAPT TO THE TOPIC" in prompt),
                ("Independence rule", "independently searchable" in prompt.lower()),
                ("Progression rule", "progressive" in prompt.lower()),
                ("Word limit mentioned", "20–100" in prompt or "20-100" in prompt),
            ]

            print("\n✅ Prompt Structure Checks:")
            for name, passed in checks:
                status = "✅" if passed else "❌"
                print(f"  {status} {name}")

        except Exception as e:
            print(f"❌ Error generating prompt: {e}")

        print("\n")


# ─────────────────────────────────────────────────────────────
# LIVE MODE — Uses real LLM
# ─────────────────────────────────────────────────────────────


def run_live_tests():
    """Run tests with real LLM using direct API calls."""
    print("\n🚀 LIVE MODE — Testing with real LLM...")
    print("Note: This requires langchain dependencies to be installed\n")

    import importlib.util
    import os
    from dotenv import load_dotenv

    load_dotenv()

    # Direct imports to avoid __init__.py chain issues
    prompts_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "researcher",
        "solution_tree",
        "prompts",
        "prompts.py",
    )
    spec = importlib.util.spec_from_file_location("prompts_direct", prompts_path)
    prompts = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(prompts)
    get_enhanced_plan_prompt = prompts.get_enhanced_plan_prompt
    PlanResult = prompts.PlanResult

    # Try to initialize LLM using direct langchain imports
    llm = None
    structured_llm = None

    # Try Google Gemini first (user has GEMINI_API_KEY in .env)
    try:
        from langchain_google_genai import ChatGoogleGenerativeAI

        # Check for either GOOGLE_API_KEY or GEMINI_API_KEY
        api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
        if api_key:
            print("🔄 Trying Google Gemini model...")
            llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash-001", temperature=1.25)
            structured_llm = llm.with_structured_output(PlanResult)
            print("✅ Google Gemini model initialized successfully\n")
        else:
            print("⚠️  GOOGLE_API_KEY/GEMINI_API_KEY not found in environment")
    except Exception as e:
        print(f"❌ Google Gemini failed: {e}")

    # Try OpenAI via OpenRouter
    if llm is None:
        try:
            from langchain_openrouter import ChatOpenRouter
            import os
            from dotenv import load_dotenv

            load_dotenv()

            if os.getenv("OPENROUTER_API_KEY"):
                print("🔄 Trying OpenAI via OpenRouter...")
                llm = ChatOpenRouter(model="openai/gpt-4o", temperature=1.25)
                structured_llm = llm.with_structured_output(PlanResult)
                print("✅ OpenAI model initialized successfully\n")
            else:
                print("⚠️  OPENROUTER_API_KEY not found in environment")
        except Exception as e:
            print(f"❌ OpenAI via OpenRouter failed: {e}")

    # Try Anthropic
    if llm is None:
        try:
            from langchain_anthropic import ChatAnthropic
            import os
            from dotenv import load_dotenv

            load_dotenv()

            if os.getenv("ANTHROPIC_API_KEY"):
                print("🔄 Trying Anthropic Claude...")
                llm = ChatAnthropic(model="claude-sonnet-4-20250514", temperature=1.25)
                structured_llm = llm.with_structured_output(PlanResult)
                print("✅ Anthropic model initialized successfully\n")
            else:
                print("⚠️  ANTHROPIC_API_KEY not found in environment")
        except Exception as e:
            print(f"❌ Anthropic failed: {e}")

    if llm is None:
        print("\n" + "=" * 60)
        print("❌ No LLM available. Live tests require one of:")
        print("   - GOOGLE_API_KEY (Google Gemini)")
        print("   - OPENROUTER_API_KEY (OpenAI/GPT-4)")
        print("   - ANTHROPIC_API_KEY (Claude)")
        print("=" * 60)
        print("\n📝 Dry-run passed. Prompt structure is valid.")
        print("   Run with API keys to test LLM output quality.")
        return

    # Initialize LLM - try multiple available models
    llm = None
    structured_llm = None

    # Try Google Gemini (available in requirements)
    try:
        print("🔄 Trying Google Gemini model...")
        llm = LlmsHouse.google_model("gemini-2.0-flash-001", temperature=1.25)
        structured_llm = llm.with_structured_output(PlanResult)
        print("✅ Google Gemini model initialized successfully\n")
    except Exception as e:
        print(f"❌ Google Gemini failed: {e}")

    # If Google failed, try OpenAI
    if llm is None:
        try:
            print("🔄 Trying OpenAI model...")
            llm = LlmsHouse.openrouter_model("openai/gpt-4o", temperature=1.25)
            structured_llm = llm.with_structured_output(PlanResult)
            print("✅ OpenAI model initialized successfully\n")
        except Exception as e:
            print(f"❌ OpenAI failed: {e}")

    # If both failed, try Anthropic
    if llm is None:
        try:
            print("🔄 Trying Anthropic model...")
            llm = LlmsHouse.anthropic_model(
                "claude-sonnet-4-20250514", temperature=1.25
            )
            structured_llm = llm.with_structured_output(PlanResult)
            print("✅ Anthropic model initialized successfully\n")
        except Exception as e:
            print(f"❌ Anthropic failed: {e}")

    if llm is None:
        print("❌ No LLM available. Cannot run live tests.")
        return

    # Initialize LLM
    try:
        llm = LlmsHouse.grok_model("grok-4-1-fast-reasoning", temperature=1.25)
        structured_llm = llm.with_structured_output(PlanResult)
        print("✅ LLM initialized successfully\n")
    except Exception as e:
        print(f"❌ Failed to initialize primary LLM: {e}")
        print("Attempting fallback...\n")
        try:
            llm = LlmsHouse.get_fallback_model(temperature=1.25)
            structured_llm = llm.with_structured_output(PlanResult)
            print("✅ Fallback LLM initialized\n")
        except Exception as e2:
            print(f"❌ Fallback also failed: {e2}")
            print("Cannot proceed without a working LLM. Exiting.")
            return

    results = []

    for i, demo in enumerate(DEMO_QUERIES):
        print(f"\n{'=' * 60}")
        print(f"Running Test {demo['id']}/10: {demo['domain']}")
        print(f'Query: "{demo["query"]}"')
        print(f"{'=' * 60}")

        try:
            # Generate prompt
            prompt = get_enhanced_plan_prompt(
                query=demo["query"],
                skill_instructions="",
                clarification_context=[],
            )

            # Invoke LLM
            result = structured_llm.invoke(prompt)
            plan = result.plan

            # Analyze
            analysis = analyze_plan(demo, plan)
            results.append(analysis)

            print(f"✅ Generated {len(plan)} queries successfully")

        except Exception as e:
            print(f"❌ Error on test {demo['id']}: {e}")
            results.append(
                {
                    "query_id": demo["id"],
                    "domain": demo["domain"],
                    "complexity": demo["complexity"],
                    "expected_range": demo["expected_range"],
                    "user_query": demo["query"],
                    "num_queries": 0,
                    "queries": [],
                    "violations": [f"❌ FAIL: LLM invocation error: {str(e)}"],
                    "scores": {},
                }
            )

    # Print full results
    print("\n\n")
    print_results(results)

    # Save results to file for later analysis
    output_file = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "planner_test_results.json",
    )
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\n📁 Results saved to: {output_file}")


# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Planner Prompt Test Harness")
    parser.add_argument(
        "--live",
        action="store_true",
        help="Run with real LLM (requires dependencies)",
    )
    args = parser.parse_args()

    if args.live:
        run_live_tests()
    else:
        # Dry run — import prompts module directly to avoid dependency issues
        import importlib.util

        prompts_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "researcher",
            "solution_tree",
            "prompts",
            "prompts.py",
        )
        spec = importlib.util.spec_from_file_location("prompts_direct", prompts_path)
        prompts = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(prompts)

        run_dry_run(prompts.get_enhanced_plan_prompt)


if __name__ == "__main__":
    main()
